# Generated by Django 4.1.7 on 2023-02-16 23:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField(auto_now_add=True)),
                (
                    "finish_date",
                    models.DateField(blank=True, default=main.models.now_plus_30),
                ),
                ("price", models.IntegerField()),
                ("paid", models.BooleanField(default=False)),
                ("type", models.CharField(default=("Month", "M"), max_length=2)),
            ],
        ),
    ]
