# Generated by Django 4.1.7 on 2023-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_client_client_code_remove_client_finish_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnkey",
            name="time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
